<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FRMU0EO" failures="9" tests="14" name="Test" time="11.815" errors="0" timestamp="2023-03-26T16:00:31 EDT">
  <testcase classname="api.tests.DDTests" name="testPostUser" time="2.616"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="0.222"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="0.326"/>
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.438">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.792">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.319">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.userTests" name="testPostUser" time="0.338"/>
  <testcase classname="api.tests.userTests" name="testGetUserByName" time="0.291">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testGetUserByName(userTests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.userTests" name="testUpdateUserByName" time="0.488">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testUpdateUserByName(userTests.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.tests.userTests" name="testDeleteUserByName" time="1.471">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testDeleteUserByName(userTests.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.TestsUsingProps" name="testPostUser" time="0.262"/>
  <testcase classname="api.tests.TestsUsingProps" name="testGetUserByName" time="0.461">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.TestsUsingProps.testGetUserByName(TestsUsingProps.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.TestsUsingProps" name="testUpdateUserByName" time="0.57">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.TestsUsingProps.testUpdateUserByName(TestsUsingProps.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.tests.TestsUsingProps" name="testDeleteUserByName" time="0.148">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.TestsUsingProps.testDeleteUserByName(TestsUsingProps.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Test -->
