<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FRMU0EO" failures="6" tests="10" name="Test" time="10.472" errors="0" timestamp="2023-03-26T13:38:30 EDT">
  <testcase classname="api.tests.DDTests" name="testPostUser" time="3.495"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="0.186"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="0.171"/>
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.252">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.262">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.DDTests" name="testGetUserByName" time="0.159">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetUserByName(DDTests.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.userTests" name="testPostUser" time="0.213"/>
  <testcase classname="api.tests.userTests" name="testGetUserByName" time="0.193">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testGetUserByName(userTests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.tests.userTests" name="testUpdateUserByName" time="0.416">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testUpdateUserByName(userTests.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.tests.userTests" name="testDeleteUserByName" time="0.191">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.userTests.testDeleteUserByName(userTests.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Test -->
